// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLOKT0tXMTFWbPMp11moWl8dutL3_Nge8',
    appId: '1:1080314411585:web:c843297e341030c26e64c0',
    messagingSenderId: '1080314411585',
    projectId: 'database-bug-sample',
    authDomain: 'database-bug-sample.firebaseapp.com',
    storageBucket: 'database-bug-sample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5E7IYOncO6JtF_O1mCYXJ3XYeerd51k4',
    appId: '1:1080314411585:android:93dcf523830c2a626e64c0',
    messagingSenderId: '1080314411585',
    projectId: 'database-bug-sample',
    storageBucket: 'database-bug-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnv8GARbLeXw9Nn83U4y61IVddefcfFO4',
    appId: '1:1080314411585:ios:11960d32881fb99f6e64c0',
    messagingSenderId: '1080314411585',
    projectId: 'database-bug-sample',
    storageBucket: 'database-bug-sample.appspot.com',
    iosClientId: '1080314411585-fm1sjshnmasgid04sdse9f1qv7rnt330.apps.googleusercontent.com',
    iosBundleId: 'com.tejasmehts.firebaseDatabaseBugSample',
  );
}
